version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - govet
    - misspell
  settings:
    errcheck:
      check-type-assertions: true
  exclusions:
    paths:
      - website
      - npm
      - pip

formatters:
  enable:
    - gofmt
