# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: kothaset

before:
  hooks:
    - go mod tidy

builds:
  - id: kothaset
    main: ./cmd/kothaset
    binary: kothaset
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/shantoislamdev/kothaset/internal/cli.Version={{.Version}}
      - -X github.com/shantoislamdev/kothaset/internal/cli.Commit={{.ShortCommit}}
      - -X github.com/shantoislamdev/kothaset/internal/cli.BuildDate={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: shantoislamdev
    name: kothaset
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

# Homebrew casks (replaces brews)
homebrew_casks:
  - name: kothaset
    repository:
      owner: shantoislamdev
      name: homebrew-tap
    directory: Casks
    homepage: "https://github.com/shantoislamdev/kothaset"
    description: "High-quality dataset generation CLI for LLM training"
    license: "Apache-2.0"

# Scoop manifest
scoops:
  - name: kothaset
    repository:
      owner: shantoislamdev
      name: scoop-bucket
    homepage: "https://github.com/shantoislamdev/kothaset"
    description: "High-quality dataset generation CLI for LLM training"
    license: Apache-2.0

# Docker images (v2 format)
dockers_v2:
  - images:
      - "ghcr.io/shantoislamdev/kothaset"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"

# Announce release
announce:
  skip: true
